"""Causal handover and actual-control ACKs for the independent joint pilot.

This is NOT reconstruction from expert annotations. A prefix must have been
issued in a fresh, logged local-teacher branch and consumed by the simulator.
The caller pins source files, verifies their hashes/identity and restores the
same physical prefix. This module admits only the observable command/ACK
projection, not physics, outcomes, labels, future actions or teacher states.
"""
from copy import deepcopy
from dataclasses import asdict

import numpy as np

from recovery_corpus import digest
from g05.utils.memlite_causal_session import CausalPlannerSession


def teacher_prefix_projection(plans, rows, *, at_control_step):
    """Exclude the command at s[t], which is not part of consumed history.

    Full immutable source files may be supplied for hash validation, but the
    projection itself reads no row/action at or beyond the handover boundary.
    A source RETRY at t must never become the new planner's previous command.
    """
    if type(at_control_step) is not int or not 0 < at_control_step <= len(rows):
        raise ValueError('A nonempty actually consumed prefix is required')
    selected=[p for p in plans if p['control_step'] < at_control_step]
    ticks=[p['control_step'] for p in selected]
    if (not ticks or any(type(t) is not int or t < 0 for t in ticks)
            or ticks[0]!=0 or ticks!=sorted(set(ticks))):
        raise ValueError('Complete ordered issuance from local branch control zero required')
    events=[]
    for p in selected:
        if (p['event_sha256']!=digest({k:v for k,v in p.items() if k!='event_sha256'})
                or p.get('source') not in ('offline_verified_local_teacher_proposal',
                                          'offline_measured_articulation_teacher_proposal')
                or p.get('not_success_label') is not True):
            raise ValueError('Not an actually logged local-branch command')
        events.append(dict(control_step=p['control_step'],context_id=p['event_sha256'],issued_by=p['source'],
            memory_before=p['memory_before'],previous_intent=p['previous_intent'],
            event=dict(validated=True,previous_outcome='UNKNOWN',ar_previous_outcome='UNKNOWN',
                task_complete=False,task_complete_claimed=False,decision=p['decision'],
                parent_goal=p['parent_goal'],active_skills_semantic_json=p['active_skills_semantic_json'],
                active_skills_text=p['active_skills_text'],memory_update=p['memory_update'])))
    controls=[]
    for step,row in enumerate(rows[:at_control_step]):
        p=[e for e in events if e['control_step']<=step][-1]
        context=row['context'];action=np.asarray(row['action_executed_raw23'],dtype=np.float32)
        if (type(row['control_step']) is not int or row['control_step']!=step
                or row['simulator_apply_ack'] is not True
                or context['context_id']!=p['context_id']
                or context['parent_goal']!=p['event']['parent_goal']
                or context['active_skills_semantic_json']!=p['event']['active_skills_semantic_json']
                or action.shape!=(23,) or not np.isfinite(action).all()
                or row.get('terminated') is not False or row.get('truncated') is not False):
            raise ValueError('Prefix has missing ACK, mixed command, invalid action or terminal state')
        controls.append(dict(control_step=step,context_id=context['context_id'],
            action_sha256=digest(action.tolist())))
    return dict(schema='actual_local_issued_prefix_v1',control_step=at_control_step,
        events=events,consumed_controls=controls,history_origin='fresh_local_teacher_branch',
        physical_outcome_input=False)


def restore_teacher_prefix(identity, projection, *, source_task, source_instance,
                           session_factory=CausalPlannerSession):
    """Create a NEW episode-local session; never mutate an existing session.

    Model identity names the new serving models. Provenance explicitly says
    the historical commands were teacher-issued, not generated by those
    weights. No learned observer feature/prediction is transplanted.
    """
    if (source_task.replace('_',' ')!=identity.task or source_instance!=identity.instance
            or set(projection)!={'schema','control_step','events','consumed_controls',
                                 'history_origin','physical_outcome_input'}
            or projection['schema']!='actual_local_issued_prefix_v1'
            or projection['history_origin']!='fresh_local_teacher_branch'
            or projection['physical_outcome_input'] is not False):
        raise ValueError('Foreign source/task/instance or non-observable prefix projection')
    end=projection['control_step'];events=projection['events'];controls=projection['consumed_controls']
    if type(end) is not int or end<=0 or len(controls)!=end or not events:
        raise ValueError('Incomplete consumed prefix')
    steps=[e['control_step'] for e in events]
    if (steps[0]!=0 or steps!=sorted(set(steps))
            or any(type(t) is not int or not 0<=t<end for t in steps)):
        raise ValueError('Future, duplicate or missing issuance')
    for tick,row in enumerate(controls):
        current=[e for e in events if e['control_step']<=tick][-1]
        if (set(row)!={'control_step','context_id','action_sha256'}
                or type(row['control_step']) is not int or row['control_step']!=tick
                or row['context_id']!=current['context_id']):
            raise ValueError('Noncontiguous or mismatched issued/consumed command')
        if (not isinstance(row['action_sha256'],str) or len(row['action_sha256'])!=64
                or any(c not in '0123456789abcdef' for c in row['action_sha256'])):
            raise ValueError('Missing applied-action identity')
    session=session_factory(identity)
    if (not isinstance(session,CausalPlannerSession) or session.identity!=identity
            or session.revision!=0 or session.installed is not None or session.closed
            or session.feedback.control_step!=0 or session.request is not None):
        raise ValueError('A fresh matching causal session is required for handover')
    for row in events:
        if (set(row)!={'control_step','context_id','issued_by','memory_before','previous_intent','event'}
                or row['memory_before']!=session.memory or row['previous_intent']!=session.previous_intent):
            raise ValueError('Broken actually issued memory recurrence')
        e=row['event']
        if (set(e)!={'validated','previous_outcome','ar_previous_outcome','task_complete','task_complete_claimed',
                     'decision','parent_goal','active_skills_semantic_json','active_skills_text','memory_update'}
                or row['issued_by'] not in ('offline_verified_local_teacher_proposal',
                                           'offline_measured_articulation_teacher_proposal')):
            raise ValueError('Non-observable or unknown historical command')
        original={key:e[key] for key in ('decision','parent_goal','active_skills_semantic_json',
                                         'active_skills_text','memory_update')}
        original.update(control_step=row['control_step'],source=row['issued_by'],not_success_label=True,
            memory_before=row['memory_before'],previous_intent=row['previous_intent'])
        if digest(original)!=row['context_id']:
            raise ValueError('Historical command content no longer matches its consumed identity')
        session.observe(identity,row['control_step'])
        token,_=session.begin_planning(identity,row['control_step'])
        session.stage(identity,token,deepcopy(row['event']))
        session.commit(identity,token)
    session.observe(identity,end)
    session.takeover_pending=True
    # The command window exists but has no fabricated historical features.
    if any(w.rows for w in session.windows):raise AssertionError('Unexpected restored observer cache')
    receipt=dict(schema='causal_teacher_handover_v1',destination_identity=asdict(identity),
        prefix_sha256=digest(projection),historical_commands_generated_by_destination_model=False,
        actual_issued_commands=len(events),consumed_prefix_controls=end,
        future_commands_restored=0,observer_features_restored=0,physical_outcomes_restored=0)
    return session,receipt


class AppliedActionClock:
    """Exactly one in-flight chunk, ACKed with the actually consumed prefix.

    A partial terminal chunk advances by its actual length, not 16. Tokens
    bind task/slot/episode/models, command revision, clock and action bytes.
    Duplicate/foreign/mismatched ACKs fail without changing session state.
    """
    def __init__(self,session):
        self.session=session
        self.pending=None
        self.generation=0

    def _check(self,identity):
        self.session._check(identity,self.session.feedback.control_step)
        if self.session.request is not None:raise ValueError('Resolve the planner transaction before actions')

    def offer(self,identity,actions):
        self._check(identity)
        if self.pending is not None or self.session.action_in_flight is not None:
            raise ValueError('Previous action chunk has not been ACKed')
        goal=self.session.low_goal(identity)
        value=np.asarray(actions,dtype=np.float32)
        if value.ndim!=2 or value.shape[1]!=23 or not 1<=len(value)<=16 or not np.isfinite(value).all():
            raise ValueError('One finite native raw23 executed prefix of at most 16 controls required')
        self.generation+=1
        record=dict(identity=asdict(identity),revision=self.session.revision,
            start_control_step=self.session.feedback.control_step,generation=self.generation,
            goal=goal,actions=value.tolist())
        token=digest(record);self.pending=dict(record,token=token)
        self.session.action_in_flight=token
        return token

    def acknowledge(self,identity,token,controls):
        self._check(identity)
        p=self.pending
        if (p is None or token!=p['token'] or token!=self.session.action_in_flight or p['revision']!=self.session.revision
                or p['start_control_step']!=self.session.feedback.control_step
                or not isinstance(controls,list) or not 1<=len(controls)<=len(p['actions'])):
            raise ValueError('Stale, duplicate, foreign or empty action ACK')
        for offset,row in enumerate(controls):
            if (set(row)!={'control_step','simulator_apply_ack','action_executed_raw23'}
                    or type(row['control_step']) is not int
                    or row['control_step']!=p['start_control_step']+offset
                    or row['simulator_apply_ack'] is not True):
                raise ValueError('Every consumed control needs an ordered real simulator ACK')
            actual=np.asarray(row['action_executed_raw23'],dtype=np.float32)
            if actual.shape!=(23,) or not np.array_equal(actual,np.asarray(p['actions'][offset],dtype=np.float32)):
                raise ValueError('Applied action differs from the offered native control')
        end=p['start_control_step']+len(controls)
        self.session.action_in_flight=None
        self.session.observe(identity,end)
        self.pending=None
        return dict(control_step=end,consumed_controls=len(controls),
            unused_controls=len(p['actions'])-len(controls),ack_sha256=digest(controls))
