"""Bind real TRAIN RGB to the consumed local-branch issued-command prefix.

Placement reference actions have no issued planner trace and are explicitly
excluded. Do not manufacture a task history from their segment annotations.
"""
import argparse
import json
from pathlib import Path
import shutil
import sys

sys.path.insert(0,str(Path(__file__).resolve().parents[1]/'code'))
from recovery_corpus import file_sha,digest
from recovery_causal_handover import teacher_prefix_projection
from skill_observation_archive import load_observation


def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--config',type=Path,required=True);p.add_argument('--config-sha256',required=True)
    p.add_argument('--inputs',type=Path,required=True);p.add_argument('--inputs-sha256',required=True)
    p.add_argument('--output',type=Path,required=True);a=p.parse_args()
    if (a.output.exists() or file_sha(a.config)!=a.config_sha256
            or file_sha(a.inputs/'manifest.json')!=a.inputs_sha256):
        raise ValueError('New output and immutable source-config/input hashes required')
    cfg=json.loads(a.config.read_text());inputs=json.loads((a.inputs/'manifest.json').read_text())
    if (inputs['schema']!='causal_runtime_initial_inputs_v1'
            or inputs['role']!='TRAIN_engineering_only_never_SFT_calibration_or_test'):
        raise ValueError('Only the already audited initial TRAIN observations')
    output=[];excluded=[]
    for row in inputs['rows']:
        case=cfg['cases'][row['case']]
        if (case['original_split']!='train' or case['recovery_split']!='train'
                or row['source_config_sha256']!=a.config_sha256
                or row['task']!=case['task'].replace('_',' ') or row['instance']!=case['instance_id']
                or row['record']['control_step']!=case['start_control']):
            raise ValueError('Foreign case/source/config/observation')
        if case['sim']['kind']!='recovery':
            excluded.append(dict(case=row['case'],reason='No actually issued command history; reference annotations are not commands'))
            continue
        directory=Path(case['sim']['directory']);branch=directory/case['sim']['branch']
        manifest=json.loads((branch/'manifest.json').read_text());source=json.loads((directory/'source.json').read_text())
        if (file_sha(branch/'manifest.json')!=case['manifest_sha256']
                or file_sha(branch/'plans.json')!=manifest['plans_sha256']
                or file_sha(branch/'transitions.jsonl')!=manifest['transitions_sha256']
                or file_sha(case['sim']['proof'])!=case['sim']['proof_sha256']
                or source['task']!=case['task'] or source['instance_id']!=case['instance_id']
                or source['source_episode']['split']!='train'):
            raise ValueError('Changed source history, split or replay proof')
        plans=json.loads((branch/'plans.json').read_text())
        controls=[json.loads(x) for x in (branch/'transitions.jsonl').read_text().splitlines()]
        projection=teacher_prefix_projection(plans,controls,at_control_step=case['start_control'])
        load_observation(a.inputs,row['record'])
        output.append(dict(row,issued_prefix=projection,issued_prefix_sha256=digest(projection),
            source_branch_manifest_sha256=case['manifest_sha256'],source_plans_sha256=manifest['plans_sha256'],
            source_controls_sha256=manifest['transitions_sha256'],source_replay_proof_sha256=case['sim']['proof_sha256'],
            history_provenance='Recorded teacher commands of the physically replayed local branch; not generated by destination H1'))
    if len(output)!=2 or len(excluded)!=1:raise ValueError('Expected two logged TRAIN recovery histories and one unlogged placement exclusion')
    a.output.mkdir(parents=True)
    for row in output:shutil.copyfile(a.inputs/row['record']['file'],a.output/row['record']['file'])
    manifest=dict(schema='actual_local_causal_handover_inputs_v1',rows=output,excluded=excluded,
        role=inputs['role'],source_inputs_sha256=a.inputs_sha256,source_config_sha256=a.config_sha256,
        physical_controls_during_test=0,rollout_success_measurement=False)
    (a.output/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
    print(json.dumps(dict(status='two_real_issued_prefixes_exported',manifest_sha256=file_sha(a.output/'manifest.json'))))


if __name__=='__main__':main()
